📝🍎🚫💰 Update Swagger API documentation to explain non-revenue service representation and prediction 'uncertainty'
mbta/api pull request #700
Opened 2023-11-08 17:32 UTC by bfauble

#### Summary of changes

**Asana Ticket:** [📝🍎🚫💰 Update Swagger API documentation to explain non-revenue service representation and prediction 'uncertainty'](https://app.asana.com/0/584764604969369/1205761861495469/f)

* added `Prediction` docs for arrival/departure uncertainty values
* added `revenue` filter docs for `Trip`, `Prediction`, and `Vehicle`.

Expected Merge Dec 7

2023-11-08 18:31 UTC, fsaid90 commented on apps/api_web/lib/api_web/controllers/prediction_controller.ex
> +              Subway
@bfauble we might want to say Subway/Light Rail

2023-11-08 18:31 UTC, fsaid90 commented on apps/api_web/lib/api_web/controllers/prediction_controller.ex
> +              Subway
Same here as above

2023-11-08 19:04 UTC, fsaid90 commented on apps/api_web/lib/api_web/swagger_helpers.ex
> +      Revenue status indicates whether or not the vehicle is accepting passengers.
Suggested reword:

"Revenue status indicates whether or not the vehicle is in revenue service - i.e. whether or not a vehicle is accepting passengers."

2023-12-12 20:02 UTC, shantigonzales requested changes
Reviewing now, seems like our name change hasn't made it in, but other than that it's looking good to me!

2023-12-21 22:12 UTC, Whoops approved these changes

2023-12-22 15:28 UTC, shantigonzales approved these changes

2023-12-22 15:32 UTC, merged